/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubgreeter;

public class GitHubGreeter {
    public String name;
    
  // Write the welcome method here
    public void welcome(String n) {
        name = n;
        System.out.println("Welcome to GitHub," + " " + name + ".");
    }
  // Write the wishes method here
    public void wishes() {
        System.out.println("Have a great semester in CSC 241");
    }
}
